[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "limstat/_version.py"
parentdir_prefix_version = "limstat-"
fallback_version  = "0.0.1"